// Code generated by chok gen fields; DO NOT EDIT.
// Source: `store` tags on this package's model structs — rerun
// `chok gen fields` after adding, renaming or removing tagged fields.

package edge

// AuditFields enumerates Audit's declared field surface (`store` tags) as
// compile-checked references. Values are the public field names the
// store's whitelists key on; they are stable under WithColumnAlias.
var AuditFields = struct {
	By string // faces: query

	ID        string // base model, query-only (resolves to the rid column)
	CreatedAt string // base model, query-only
	UpdatedAt string // base model, query-only
}{
	By: "by",

	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// AuditBaseFields enumerates AuditBase's declared field surface (`store` tags) as
// compile-checked references. Values are the public field names the
// store's whitelists key on; they are stable under WithColumnAlias.
var AuditBaseFields = struct {
	Actor string // faces: query

	ID        string // base model, query-only (resolves to the rid column)
	CreatedAt string // base model, query-only
	UpdatedAt string // base model, query-only
}{
	Actor: "actor",

	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// ContactFields enumerates Contact's declared field surface (`store` tags) as
// compile-checked references. Values are the public field names the
// store's whitelists key on; they are stable under WithColumnAlias.
var ContactFields = struct {
	ProfileID string // faces: query
	BadgeID   string // faces: query
	Note      string // faces: query, update

	ID        string // base model, query-only (resolves to the rid column)
	CreatedAt string // base model, query-only
	UpdatedAt string // base model, query-only
}{
	ProfileID: "profile_id",
	BadgeID:   "badge_id",
	Note:      "note",

	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// EntryFields enumerates Entry's declared field surface (`store` tags) as
// compile-checked references. Values are the public field names the
// store's whitelists key on; they are stable under WithColumnAlias.
var EntryFields = struct {
	Title string // faces: query

	ID        string // base model, query-only (resolves to the rid column)
	CreatedAt string // base model, query-only
	UpdatedAt string // base model, query-only
}{
	Title: "title",

	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// ParentFields enumerates Parent's declared field surface (`store` tags) as
// compile-checked references. Values are the public field names the
// store's whitelists key on; they are stable under WithColumnAlias.
var ParentFields = struct {
	Note string // faces: query

	ID        string // base model, query-only (resolves to the rid column)
	CreatedAt string // base model, query-only
	UpdatedAt string // base model, query-only
}{
	Note: "note",

	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// TicketFields enumerates Ticket's declared field surface (`store` tags) as
// compile-checked references. Values are the public field names the
// store's whitelists key on; they are stable under WithColumnAlias.
var TicketFields = struct {
	Subject string // faces: query

	ID        string // base model, query-only (resolves to the rid column)
	CreatedAt string // base model, query-only
	UpdatedAt string // base model, query-only
}{
	Subject: "subject",

	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// hiddenAuditFields enumerates hiddenAudit's declared field surface (`store` tags) as
// compile-checked references. Values are the public field names the
// store's whitelists key on; they are stable under WithColumnAlias.
var hiddenAuditFields = struct {
	Ref string // faces: query

	ID        string // base model, query-only (resolves to the rid column)
	CreatedAt string // base model, query-only
	UpdatedAt string // base model, query-only
}{
	Ref: "ref",

	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}
