package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

func TestRunDocsGen_CheckCoversFrameworkTablesSource(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "docs"), 0o755); err != nil {
		t.Fatal(err)
	}
	markerDoc := "<!-- gen:components -->\nold\n<!-- /gen:components -->\n"
	for _, path := range []string{"README.md", "README_zh.md", filepath.Join("docs", "design.md")} {
		if err := os.WriteFile(filepath.Join(root, path), []byte(markerDoc), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	cmd := &cobra.Command{}
	cmd.SetOut(&bytes.Buffer{})
	cmd.SetErr(&bytes.Buffer{})
	if err := runDocsGen(cmd, root, false); err != nil {
		t.Fatal(err)
	}
	generated := filepath.Join(root, "db", "framework_tables_gen.go")
	if raw, err := os.ReadFile(generated); err != nil || !strings.Contains(string(raw), "Code generated by chok docs gen") {
		t.Fatalf("framework table source was not generated: err=%v\n%s", err, raw)
	}
	if err := runDocsGen(cmd, root, true); err != nil {
		t.Fatalf("freshly generated repository must pass --check: %v", err)
	}

	if err := os.Remove(generated); err != nil {
		t.Fatal(err)
	}
	var stderr bytes.Buffer
	cmd.SetErr(&stderr)
	if err := runDocsGen(cmd, root, true); err == nil || !strings.Contains(stderr.String(), "framework_tables_gen.go") {
		t.Fatalf("--check must report a missing framework table source: err=%v stderr=%q", err, stderr.String())
	}

	if err := runDocsGen(cmd, root, false); err != nil {
		t.Fatal(err)
	}
	raw, err := os.ReadFile(generated)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(generated, append(raw, []byte("// stale\n")...), 0o644); err != nil {
		t.Fatal(err)
	}
	stderr.Reset()
	if err := runDocsGen(cmd, root, true); err == nil || !strings.Contains(stderr.String(), "framework_tables_gen.go") {
		t.Fatalf("--check must report a stale framework table source: err=%v stderr=%q", err, stderr.String())
	}
}
