package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/zynthara/chok/v2/internal/fieldgen"
)

// runGenFieldsForTest drives the real cobra command tree ("gen fields")
// against one or more dirs and returns stdout+stderr plus the first
// dir's generated file content.
func runGenFieldsForTest(t *testing.T, dirs []string, args ...string) (out string, gen string, err error) {
	t.Helper()
	cmd := genCmd()
	var sb strings.Builder
	cmd.SetOut(&sb)
	cmd.SetErr(&sb)
	cliArgs := []string{"fields"}
	for _, d := range dirs {
		cliArgs = append(cliArgs, "--dir", d)
	}
	cmd.SetArgs(append(cliArgs, args...))
	err = cmd.Execute()
	raw, readErr := os.ReadFile(filepath.Join(dirs[0], fieldgen.GenFileName))
	if readErr == nil {
		gen = string(raw)
	}
	return sb.String(), gen, err
}

func writeModel(t *testing.T, dir, name, src string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
}

const blogLikeModel = `package main

import "github.com/zynthara/chok/v2/db"

type Post struct {
	db.OwnedSoftDeleteModel
	Title  string ` + "`json:\"title\" store:\"query,update\"`" + `
	Status string ` + "`json:\"status\" store:\"query,update\"`" + `
}
`

func TestGenFields_GeneratesFieldReferences(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "main.go", blogLikeModel)

	out, gen, err := runGenFieldsForTest(t, []string{dir})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "written") {
		t.Fatalf("first run must write, got %q", out)
	}
	for _, want := range []string{
		"// Code generated by chok gen fields; DO NOT EDIT.",
		"package main",
		"var PostFields = struct {",
		`Title:  "title",`,
		`ID:        "id",`,
	} {
		if !strings.Contains(gen, want) {
			t.Errorf("generated file must contain %q:\n%s", want, gen)
		}
	}
}

func TestGenFields_IdempotentAndCheckMode(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "main.go", blogLikeModel)

	_, gen1, err := runGenFieldsForTest(t, []string{dir})
	if err != nil {
		t.Fatal(err)
	}
	out2, gen2, err := runGenFieldsForTest(t, []string{dir})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out2, "unchanged") {
		t.Fatalf("second run must be a no-op, got %q", out2)
	}
	if gen1 != gen2 {
		t.Fatal("gen fields must be byte-stable across runs")
	}

	if _, _, err := runGenFieldsForTest(t, []string{dir}, "--check"); err != nil {
		t.Fatalf("--check on a current file must pass: %v", err)
	}
	writeModel(t, dir, "main.go", strings.Replace(blogLikeModel, `json:"title"`, `json:"headline"`, 1))
	if out, _, err := runGenFieldsForTest(t, []string{dir}, "--check"); err == nil {
		t.Fatalf("--check must fail after a model rename, got %q", out)
	}

	// --check never writes: the file on disk still carries the old name.
	raw, _ := os.ReadFile(filepath.Join(dir, fieldgen.GenFileName))
	if !strings.Contains(string(raw), `"title"`) {
		t.Fatal("--check must not modify the generated file")
	}
}

func TestGenFields_NothingToDoAndOrphanRemoval(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "dto.go", "package main\n\ntype Req struct {\n\tQ string `json:\"q\"`\n}\n")

	out, _, err := runGenFieldsForTest(t, []string{dir})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "nothing to do") {
		t.Fatalf("tag-less dir must report nothing to do, got %q", out)
	}

	// Simulate models losing their tags after a generated file existed.
	orphan := filepath.Join(dir, fieldgen.GenFileName)
	if err := os.WriteFile(orphan, []byte("// Code generated by chok gen fields; DO NOT EDIT.\n\npackage main\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if out, _, err := runGenFieldsForTest(t, []string{dir}, "--check"); err == nil {
		t.Fatalf("--check must flag an orphaned generated file, got %q", out)
	}
	out, _, err = runGenFieldsForTest(t, []string{dir})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "removed") {
		t.Fatalf("orphaned generated file must be removed, got %q", out)
	}
	if _, err := os.Stat(orphan); !os.IsNotExist(err) {
		t.Fatal("orphan must be gone from disk")
	}
}

func TestGenFields_ConflictingSymbolFailsLoud(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "main.go", blogLikeModel)
	writeModel(t, dir, "clash.go", "package main\n\nvar PostFields = 1\n")

	_, _, err := runGenFieldsForTest(t, []string{dir})
	if err == nil || !strings.Contains(err.Error(), "PostFields") {
		t.Fatalf("existing PostFields declaration must abort generation, got %v", err)
	}
}

func TestGenFields_MultipleDirs(t *testing.T) {
	dirA := t.TempDir()
	dirB := t.TempDir()
	writeModel(t, dirA, "a.go", blogLikeModel)
	writeModel(t, dirB, "b.go", `package model

type Tag struct {
	Label string `+"`json:\"label\" store:\"query\"`"+`
}
`)
	out, genA, err := runGenFieldsForTest(t, []string{dirA, dirB})
	if err != nil {
		t.Fatal(err)
	}
	if c := strings.Count(out, "written"); c != 2 {
		t.Fatalf("both dirs must be generated, got %q", out)
	}
	if !strings.Contains(genA, "PostFields") {
		t.Fatal("dir A must carry its own models")
	}
	rawB, err := os.ReadFile(filepath.Join(dirB, fieldgen.GenFileName))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(rawB), "package model") || !strings.Contains(string(rawB), "TagFields") {
		t.Fatalf("dir B must adopt its own package and models:\n%s", rawB)
	}
}

func TestGenFields_WarningsSurfaceOnStderr(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "m.go", `package main

type custom struct{ X string }

type Post struct {
	custom
	Title string `+"`json:\"title\" store:\"query\"`"+`
}
`)
	out, _, err := runGenFieldsForTest(t, []string{dir})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "warning:") || !strings.Contains(out, "custom") {
		t.Fatalf("unknown embeds must warn on stderr, got %q", out)
	}
}
