package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// runSyncForTest drives the real cobra command against a temp project
// dir and returns stdout+stderr plus the generated file's content.
func runSyncForTest(t *testing.T, dir string, args ...string) (out string, gen string, err error) {
	t.Helper()
	cmd := syncCmd()
	var sb strings.Builder
	cmd.SetOut(&sb)
	cmd.SetErr(&sb)
	cmd.SetArgs(append([]string{
		"--config", filepath.Join(dir, "chok.yaml"),
		"--dir", dir,
	}, args...))
	err = cmd.Execute()
	raw, readErr := os.ReadFile(filepath.Join(dir, genFileName))
	if readErr == nil {
		gen = string(raw)
	}
	return sb.String(), gen, err
}

func writeYAML(t *testing.T, dir, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, "chok.yaml"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestSync_SectionPresenceDrivesAssembly(t *testing.T) {
	dir := t.TempDir()
	writeYAML(t, dir, `
http:
  addr: ":8080"
db:
  driver: sqlite
  sqlite: {path: app.db}
redis:
  enabled: false
`)
	_, gen, err := runSyncForTest(t, dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"// Code generated by chok sync; DO NOT EDIT.",
		"package main",
		"web.Module(),",
		"db.Module(),",
		"redis.Module(),", // enabled:false still links — runtime switch stays yaml's
		`"github.com/zynthara/chok/v2/web"`,
	} {
		if !strings.Contains(gen, want) {
			t.Errorf("generated file must contain %q:\n%s", want, gen)
		}
	}
	for _, absent := range []string{"account.Module", "audit.Module", "swagger.Module"} {
		if strings.Contains(gen, absent) {
			t.Errorf("sections not in yaml must not be assembled (%s):\n%s", absent, gen)
		}
	}
}

func TestSync_IdempotentAndCheckMode(t *testing.T) {
	dir := t.TempDir()
	writeYAML(t, dir, "http:\n  addr: \":0\"\n")

	out1, gen1, err := runSyncForTest(t, dir)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out1, "written") {
		t.Fatalf("first run must write, got %q", out1)
	}
	out2, gen2, err := runSyncForTest(t, dir)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out2, "unchanged") {
		t.Fatalf("second run must be a no-op, got %q", out2)
	}
	if gen1 != gen2 {
		t.Fatal("sync must be byte-stable across runs")
	}

	if _, _, err := runSyncForTest(t, dir, "--check"); err != nil {
		t.Fatalf("--check on a current file must pass: %v", err)
	}
	writeYAML(t, dir, "http:\n  addr: \":0\"\ndb:\n  driver: sqlite\n")
	if _, _, err := runSyncForTest(t, dir, "--check"); err == nil {
		t.Fatal("--check must fail when the yaml gained a section")
	}
}

func TestSync_ProviderRegistrationLines(t *testing.T) {
	dir := t.TempDir()
	writeYAML(t, dir, `
http: {addr: ":0"}
db: {driver: sqlite}
account:
  signing_key: k
  providers:
    google:
      enabled: true
      client_id: id
    github:
      enabled: false
    custom-idp:
      enabled: true
`)
	out, gen, err := runSyncForTest(t, dir)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(gen, "account.Module(account.WithProviders(google.Provider()))") {
		t.Errorf("enabled blessed provider must be registered:\n%s", gen)
	}
	if strings.Contains(gen, "github.Provider()") {
		t.Errorf("enabled:false provider must not link:\n%s", gen)
	}
	if !strings.Contains(out, "custom-idp") {
		t.Errorf("unknown provider must warn, got %q", out)
	}
}

func TestSync_NamedDBInstances(t *testing.T) {
	dir := t.TempDir()
	writeYAML(t, dir, `
http: {addr: ":0"}
db:
  driver: postgres
  instances:
    read: {driver: postgres}
    write: {driver: postgres}
`)
	_, gen, err := runSyncForTest(t, dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{`db.Module(db.As("read")),`, `db.Module(db.As("write")),`} {
		if !strings.Contains(gen, want) {
			t.Errorf("named instance must assemble (%s):\n%s", want, gen)
		}
	}
}

func TestSync_HardDependencyWarning(t *testing.T) {
	dir := t.TempDir()
	// swagger hard-needs http; account hard-needs db — both absent.
	writeYAML(t, dir, `
swagger: {title: X}
account: {signing_key: k}
`)
	out, _, err := runSyncForTest(t, dir)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, `swagger requires the "http" module`) {
		t.Errorf("missing hard-dep warning for swagger→http, got %q", out)
	}
	if !strings.Contains(out, `account requires the "db" module`) {
		t.Errorf("missing hard-dep warning for account→db, got %q", out)
	}
}

func TestSync_PackageNameDetection(t *testing.T) {
	dir := t.TempDir()
	writeYAML(t, dir, "http: {addr: \":0\"}\n")
	if err := os.WriteFile(filepath.Join(dir, "app.go"), []byte("package bootstrap\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	_, gen, err := runSyncForTest(t, dir)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(gen, "package bootstrap") {
		t.Errorf("generated file must adopt the directory's package:\n%s", gen)
	}
}
