// Code generated by chok gen fields; DO NOT EDIT.
// Source: `store` tags on this package's model structs — rerun
// `chok gen fields` after adding, renaming or removing tagged fields.

package main

// PostFields enumerates Post's declared field surface (`store` tags) as
// compile-checked references. Values are the public field names the
// store's whitelists key on; they are stable under WithColumnAlias.
var PostFields = struct {
	Title   string // faces: query, update
	Content string // faces: update
	Status  string // faces: query, update

	ID        string // base model, query-only (resolves to the rid column)
	CreatedAt string // base model, query-only
	UpdatedAt string // base model, query-only
}{
	Title:   "title",
	Content: "content",
	Status:  "status",

	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}
