// Code generated by chok sync; DO NOT EDIT.
// Source: chok.yaml — rerun `chok sync` after adding or removing module sections.
//
// Customize modules in your own code with chok.Override(...); this
// file always mirrors the yaml.

package main

import (
	"github.com/zynthara/chok/v2"

	"github.com/zynthara/chok/v2/account"
	"github.com/zynthara/chok/v2/db"
	"github.com/zynthara/chok/v2/health"
	"github.com/zynthara/chok/v2/log"
	"github.com/zynthara/chok/v2/metrics"
	"github.com/zynthara/chok/v2/swagger"
	"github.com/zynthara/chok/v2/web"
)

// chokModules is the assembly derived from chok.yaml: one module per
// section present. yaml `enabled` remains the runtime switch.
func chokModules() chok.Option {
	return chok.Use(
		log.Module(),
		web.Module(),
		health.Module(),
		metrics.Module(),
		swagger.Module(),
		db.Module(),
		account.Module(),
	)
}
