// Code generated by chok gen fields; DO NOT EDIT.
// Source: `store` tags on this package's model structs — rerun
// `chok gen fields` after adding, renaming or removing tagged fields.

package fixture

// ArticleFields enumerates Article's declared field surface (`store` tags) as
// compile-checked references. Values are the public field names the
// store's whitelists key on; they are stable under WithColumnAlias.
var ArticleFields = struct {
	Code         string // faces: query
	Title        string // faces: query, update
	Body         string // faces: update
	Secret       string // faces: query
	InternalNote string // faces: query
	HTTPStatus   string // faces: query
	LegacyBody   string // faces: update
	Aliased      string // faces: query
	PublishedAt  string // faces: query

	ID        string // base model, query-only (resolves to the rid column)
	CreatedAt string // base model, query-only
	UpdatedAt string // base model, query-only
}{
	Code:         "code",
	Title:        "title",
	Body:         "body",
	Secret:       "secret",
	InternalNote: "internal_note",
	HTTPStatus:   "http_status",
	LegacyBody:   "body_raw",
	Aliased:      "aliased",
	PublishedAt:  "published_at",

	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// ShadowIDFields enumerates ShadowID's declared field surface (`store` tags) as
// compile-checked references. Values are the public field names the
// store's whitelists key on; they are stable under WithColumnAlias.
var ShadowIDFields = struct {
	PublicID string // faces: query
	Name     string // faces: query, update
	Kind     string // faces: query

	CreatedAt string // base model, query-only
	UpdatedAt string // base model, query-only
}{
	PublicID: "id",
	Name:     "name",
	Kind:     "kind",

	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// WalletFields enumerates Wallet's declared field surface (`store` tags) as
// compile-checked references. Values are the public field names the
// store's whitelists key on; they are stable under WithColumnAlias.
var WalletFields = struct {
	Money string // faces: query
	Flags string // faces: query, update

	ID        string // base model, query-only (resolves to the rid column)
	CreatedAt string // base model, query-only
	UpdatedAt string // base model, query-only
}{
	Money: "money",
	Flags: "flags",

	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}
