package docgen

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"

	"github.com/zynthara/chok/v2/internal/blessed"
)

// FrameworkTablesSource renders db's checked-in catalog from the schema
// declarations of chok's built-in components.
func FrameworkTablesSource() ([]byte, error) {
	tables, err := blessed.SchemaTables()
	if err != nil {
		return nil, err
	}

	var source bytes.Buffer
	source.WriteString("// Code generated by chok docs gen. DO NOT EDIT.\n\n")
	source.WriteString("package db\n\n")
	source.WriteString("// frameworkTables is the sorted catalog aggregated from the schema\n")
	source.WriteString("// declarations of chok's built-in components.\n")
	source.WriteString("var frameworkTables = []string{\n")
	for _, table := range tables {
		fmt.Fprintf(&source, "\t%s,\n", strconv.Quote(table))
	}
	source.WriteString("}\n")

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("docgen: format framework table source: %w", err)
	}
	return formatted, nil
}
