package docgen

import (
	"encoding/json"
	"reflect"
	"strconv"
	"strings"

	"github.com/zynthara/chok/v2/account/providers/apple"
	"github.com/zynthara/chok/v2/account/providers/facebook"
	"github.com/zynthara/chok/v2/account/providers/github"
	"github.com/zynthara/chok/v2/account/providers/google"
	"github.com/zynthara/chok/v2/conf"
	"github.com/zynthara/chok/v2/internal/blessed"
	"github.com/zynthara/chok/v2/kernel"
)

// JSONSchema renders docs/chok.schema.json: the editor-completion and
// CI-validation schema for chok.yaml. Structural by design — types,
// defaults and the enums the SPEC freezes; behavioural validation
// stays in each Options.Validate.
func JSONSchema() ([]byte, error) {
	root := map[string]any{
		"$schema":     "https://json-schema.org/draft/2020-12/schema",
		"$id":         "https://github.com/zynthara/chok/blob/main/docs/chok.schema.json",
		"title":       "chok.yaml",
		"description": "Configuration of a chok v2 application. Generated by `chok docs gen`; module sections present in the file are also what `chok sync` assembles.",
		"type":        "object",
		// Business sections (chok.Section[T]) are user-defined.
		"additionalProperties": true,
	}
	props := map[string]any{}
	for _, m := range blessed.Modules() {
		d := m.New().Describe()
		section := kernel.SectionKeyOf(d)
		s := sectionSchema(m, d)
		if m.MultiInstance {
			// instances.<name> mirrors the section (minus instances).
			inner := sectionSchema(m, d)
			innerProps := inner["properties"].(map[string]any)
			s["properties"].(map[string]any)[conf.ReservedInstancesKey] = map[string]any{
				"type":        "object",
				"description": "Named instances (framework-owned subtree): every child is a full section.",
				"additionalProperties": map[string]any{
					"type":                 "object",
					"properties":           innerProps,
					"additionalProperties": false,
				},
			}
		}
		props[section] = s
	}
	root["properties"] = props
	return json.MarshalIndent(root, "", "  ")
}

func sectionSchema(m blessed.Module, d kernel.Descriptor) map[string]any {
	s := map[string]any{
		"type":                 "object",
		"description":          m.DescEN,
		"additionalProperties": false,
	}
	props := map[string]any{}
	if d.Options != nil {
		t := reflect.TypeOf(d.Options)
		for t.Kind() == reflect.Ptr {
			t = t.Elem()
		}
		structSchema(t, "", m.Enums, props)
	}
	s["properties"] = props
	return s
}

// structSchema fills props with one entry per field of t, recursing
// into nested option structs. path is the section-relative dot path
// used for enum hints.
func structSchema(t reflect.Type, path string, enums map[string][]string, props map[string]any) {
	for i := range t.NumField() {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		key := mapKeyOf(f)
		full := key
		if path != "" {
			full = path + "." + key
		}
		props[key] = fieldSchema(f, full, enums)
	}
}

func fieldSchema(f reflect.StructField, path string, enums map[string][]string) map[string]any {
	ft := f.Type
	for ft.Kind() == reflect.Ptr {
		ft = ft.Elem()
	}
	s := typeSchema(ft, path, enums)

	if def := f.Tag.Get("default"); def != "" {
		if v, ok := typedDefault(ft, def); ok {
			s["default"] = v
		}
	}
	if f.Tag.Get("sensitive") == "true" {
		s["writeOnly"] = true
		desc := "Sensitive: redacted in logs; inject via environment in production."
		if d, ok := s["description"].(string); ok && d != "" {
			desc = d + " " + desc
		}
		s["description"] = desc
	}
	if enum, ok := enums[path]; ok {
		vals := make([]any, len(enum))
		for i, e := range enum {
			vals[i] = e
		}
		s["enum"] = vals
		delete(s, "type") // enum constrains on its own; keeps yaml-ls happy
	}
	return s
}

func typeSchema(t reflect.Type, path string, enums map[string][]string) map[string]any {
	switch {
	case t.String() == "time.Duration":
		return map[string]any{
			"type":        []any{"string", "integer"},
			"description": "Go duration (e.g. 30s, 1h30m); bare integers are nanoseconds.",
		}
	case t.String() == "time.Time":
		return map[string]any{"type": "string", "format": "date-time"}
	case t.Kind() == reflect.Bool:
		return map[string]any{"type": "boolean"}
	case t.Kind() >= reflect.Int && t.Kind() <= reflect.Uint64:
		return map[string]any{"type": "integer"}
	case t.Kind() == reflect.Float32 || t.Kind() == reflect.Float64:
		return map[string]any{"type": "number"}
	case t.Kind() == reflect.String:
		return map[string]any{"type": "string"}
	case t.Kind() == reflect.Slice:
		return map[string]any{"type": "array", "items": typeSchema(t.Elem(), path+"[]", enums)}
	case t.Kind() == reflect.Map:
		if path == "providers" {
			return providersSchema()
		}
		return map[string]any{"type": "object", "additionalProperties": true}
	case t.Kind() == reflect.Struct && !isAtomicStruct(t):
		props := map[string]any{}
		structSchema(t, path, enums, props)
		return map[string]any{"type": "object", "properties": props, "additionalProperties": false}
	default:
		return map[string]any{} // interface/any: unconstrained
	}
}

// providersSchema types account.providers: the four blessed providers
// get their real option shapes; unknown names stay open for custom
// ProviderSpecs.
func providersSchema() map[string]any {
	samples := map[string]any{
		"google":   google.Options{},
		"github":   github.Options{},
		"facebook": facebook.Options{},
		"apple":    apple.Options{},
	}
	provProps := map[string]any{}
	for _, p := range blessed.Providers() {
		shape := map[string]any{
			"enabled": map[string]any{
				"type":        "boolean",
				"default":     false,
				"description": "Runtime switch; the provider must also be assembled (chok sync emits the registration when true).",
			},
		}
		// Provider Options structs are decoded from the raw map — walk
		// them for completion keys. Secrets ride conf's map-key
		// heuristic at runtime, so mark the same suspects writeOnly.
		if opt, ok := samples[p.Name]; ok {
			t := reflect.TypeOf(opt)
			for i := range t.NumField() {
				f := t.Field(i)
				if !f.IsExported() {
					continue
				}
				key := mapKeyOf(f)
				fs := typeSchema(f.Type, key, nil)
				if sensitiveKey(key) {
					fs["writeOnly"] = true
				}
				shape[key] = fs
			}
		}
		provProps[p.Name] = map[string]any{
			"type":                 "object",
			"properties":           shape,
			"additionalProperties": true,
		}
	}
	return map[string]any{
		"type":                 "object",
		"description":          "OAuth providers keyed by name; enabled:true requires the provider to be assembled (account.WithProviders / chok sync).",
		"properties":           provProps,
		"additionalProperties": map[string]any{"type": "object"},
	}
}

// sensitiveKey mirrors conf's redaction heuristic for provider map
// keys (schema-side marking only; runtime redaction lives in conf).
func sensitiveKey(name string) bool {
	n := strings.ToLower(name)
	for _, tok := range []string{"secret", "password", "private_key", "token", "signing_key", "api_key", "dsn"} {
		if strings.Contains(n, tok) {
			return true
		}
	}
	return false
}

func typedDefault(t reflect.Type, def string) (any, bool) {
	switch {
	case t.String() == "time.Duration":
		return def, true // keep the human form ("15s")
	case t.Kind() == reflect.Bool:
		b, err := strconv.ParseBool(def)
		return b, err == nil
	case t.Kind() >= reflect.Int && t.Kind() <= reflect.Uint64:
		n, err := strconv.ParseInt(def, 10, 64)
		return n, err == nil
	case t.Kind() == reflect.Float32 || t.Kind() == reflect.Float64:
		fl, err := strconv.ParseFloat(def, 64)
		return fl, err == nil
	case t.Kind() == reflect.Slice:
		// conf treats a scalar default as a one-element list ("stdout").
		return []any{def}, true
	default:
		return def, true
	}
}
