.DEFAULT_GOAL := run

.PHONY: run
run: ## go run the app (chok.yaml next to it)
	go run .

.PHONY: build
build: ## Build the binary
	go build -o {{.Name}} .

.PHONY: sync
sync: ## Regenerate chok_modules_gen.go after editing chok.yaml
	chok sync

.PHONY: test
test:
	go test ./...

.PHONY: tidy
tidy:
	go mod tidy
