// Code generated by chok docs gen. DO NOT EDIT.

package db

// frameworkTables is the sorted catalog aggregated from the schema
// declarations of chok's built-in components.
var frameworkTables = []string{
	"audit_logs",
	"casbin_rule",
	"identities",
	"schema_migrations",
	"schema_migrations_chok_account",
	"schema_migrations_chok_audit",
	"schema_migrations_chok_authz",
	"users",
}
